name: Build and publish Windows .exe

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build exe
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller -F -n meshtastic_pygui meshtastic_pygui/__main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: MeshFlash
          path: dist
